FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build   
WORKDIR /src
COPY ["TagsApi/TagsApi.csproj", "TagsApi/"]       
...
RUN dotnet restore                                 
RUN dotnet publish -o /app/publish                 

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final 
COPY --from=build /app/publish .                  
ENTRYPOINT ["dotnet", "TagsApi.dll"]               